package arraylistgui.gui;

import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 * @author alberto
 */
public class ArrayListGUI extends javax.swing.JFrame {

   /**
    * Creates new form ArrayListGUI
    */
   public ArrayListGUI() {
      // Inicialização manual de algumas coisas...
      tableModel = new TableModelVeiculo(); // Model personalizado.
      this.setTitle("ArrayListGUI - Revenda de carros"); // Atualiza o título da janela.
      this.setResizable(false); // Fixa o tamanho da janela.
      initComponents();
      jtListagem.setDragEnabled(false);
      jtListagem.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
   }
   
   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
    * content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jtModelo = new javax.swing.JTextField();
      jtMarca = new javax.swing.JTextField();
      jtCor = new javax.swing.JTextField();
      jtPlaca = new javax.swing.JFormattedTextField();
      jtAno = new javax.swing.JFormattedTextField();
      jtValor = new javax.swing.JFormattedTextField();
      btnLimpar = new javax.swing.JButton();
      btnAlterar = new javax.swing.JButton();
      btnRemover = new javax.swing.JButton();
      btnInserir = new javax.swing.JButton();
      jScrollPane1 = new javax.swing.JScrollPane();
      jtListagem = new javax.swing.JTable();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setText("Marca");

      jLabel2.setText("Modelo");

      jLabel3.setText("Cor");

      jLabel4.setText("Placa");

      jLabel5.setText("Ano");

      jLabel6.setText("Valor");

      btnLimpar.setText("Limpar");
      btnLimpar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnLimparActionPerformed(evt);
         }
      });

      btnAlterar.setText("Alterar");
      btnAlterar.setEnabled(false);
      btnAlterar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAlterarActionPerformed(evt);
         }
      });

      btnRemover.setText("Remover");
      btnRemover.setEnabled(false);
      btnRemover.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRemoverActionPerformed(evt);
         }
      });

      btnInserir.setText("Inserir");
      btnInserir.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnInserirActionPerformed(evt);
         }
      });

      jtListagem.setModel(tableModel);
      jtListagem.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseReleased(java.awt.event.MouseEvent evt) {
            jtListagemMouseReleased(evt);
         }
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            jtListagemMouseClicked(evt);
         }
      });
      jScrollPane1.setViewportView(jtListagem);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel2)
                     .addComponent(jLabel3)
                     .addComponent(jLabel4))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtAno))
                     .addComponent(jtModelo)
                     .addComponent(jtCor)))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel1)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(jtMarca))
               .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
      );

      layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnInserir, btnLimpar, btnRemover});

      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel1)
               .addComponent(jtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel2)
               .addComponent(jtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel3)
               .addComponent(jtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel4)
               .addComponent(jtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel5)
               .addComponent(jtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jLabel6)
               .addComponent(jtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnLimpar)
               .addComponent(btnAlterar)
               .addComponent(btnRemover)
               .addComponent(btnInserir))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
      jtMarca.setText("");
      jtModelo.setText("");
      jtCor.setText("");
      jtPlaca.setText("");
      jtAno.setText("");
      jtValor.setText("");
      jtListagem.clearSelection();
      btnRemover.setEnabled(false);
      btnAlterar.setEnabled(false);
   }//GEN-LAST:event_btnLimparActionPerformed

   private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
      int row = jtListagem.getSelectedRow();
      if (row >= 0) {
         Veiculo v = constroiVeiculo();
         if (v != null) tableModel.update(row, v);
      }
   }//GEN-LAST:event_btnAlterarActionPerformed

   private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
      int row = jtListagem.getSelectedRow();
      if (row >= 0) {
         tableModel.remove(row);
         btnLimparActionPerformed(null);
      }
   }//GEN-LAST:event_btnRemoverActionPerformed

   private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
      Veiculo novo = constroiVeiculo();
      if (novo != null) {
         tableModel.add(novo);
         btnLimparActionPerformed(null);
      }
   }//GEN-LAST:event_btnInserirActionPerformed

   private void jtListagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListagemMouseClicked
      int row = jtListagem.getSelectedRow();
      if (row >= 0) {
         btnRemover.setEnabled(true);
         btnAlterar.setEnabled(true);
         Veiculo v = tableModel.select(row);
         jtMarca.setText(v.getMarca());
         jtModelo.setText(v.getModelo());
         jtCor.setText(v.getCor());
         jtPlaca.setText(v.getPlaca());
         jtAno.setText(v.getAno() + "");
         jtValor.setText(v.getValor() + "");
      }
   }//GEN-LAST:event_jtListagemMouseClicked

   private void jtListagemMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtListagemMouseReleased
      jtListagemMouseClicked(null);
   }//GEN-LAST:event_jtListagemMouseReleased

   /**
    * Constrói um objeto {@link Veiculo} a partir de componentes da interface gráfica.
    * @return {@link Veiculo} recém criado ou null se há erro nos dados digitados.
    */
   protected Veiculo constroiVeiculo() {
      try {
         Veiculo v = new Veiculo();
         v.setMarca(jtMarca.getText());
         v.setModelo(jtModelo.getText());
         v.setCor(jtCor.getText());
         v.setPlaca(jtPlaca.getText());
         v.setAno(Integer.parseInt(jtAno.getText()));
         v.setValor(Float.parseFloat(jtValor.getText()));
         return v;
      } catch (Exception e) {
          JOptionPane.showMessageDialog(this, "Dado(s) de entrada invalido(s)!");
      }
      return null;
   }
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(ArrayListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(ArrayListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(ArrayListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(ArrayListGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
        //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new ArrayListGUI().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   protected javax.swing.JButton btnAlterar;
   protected javax.swing.JButton btnInserir;
   protected javax.swing.JButton btnLimpar;
   protected javax.swing.JButton btnRemover;
   protected javax.swing.JLabel jLabel1;
   protected javax.swing.JLabel jLabel2;
   protected javax.swing.JLabel jLabel3;
   protected javax.swing.JLabel jLabel4;
   protected javax.swing.JLabel jLabel5;
   protected javax.swing.JLabel jLabel6;
   protected javax.swing.JScrollPane jScrollPane1;
   protected javax.swing.JFormattedTextField jtAno;
   protected javax.swing.JTextField jtCor;
   protected javax.swing.JTable jtListagem;
   protected javax.swing.JTextField jtMarca;
   protected javax.swing.JTextField jtModelo;
   protected javax.swing.JFormattedTextField jtPlaca;
   protected javax.swing.JFormattedTextField jtValor;
   // End of variables declaration//GEN-END:variables

   protected TableModelVeiculo tableModel;
}
