package posto.view;

import posto.controller.PostoController;
import posto.model.TableModelPosto;
import posto.model.TableModelCombustivel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JFormattedTextField;

/**
 * @author Zilly
 */
public class PostoGUI extends javax.swing.JFrame {

    private PostoController controller;
    private TableModelPosto tabelaPosto;
    private TableModelCombustivel tabelaComb;

    /**
     * Creates new form PostoGUI
     */
    public PostoGUI() {
        tabelaPosto = new TableModelPosto();
        //tabela é criada com arrayList vazio por default
        tabelaComb = new TableModelCombustivel();
        controller = new PostoController(this, tabelaPosto, tabelaComb);

        initComponents();
        //jtTabelaPosto.setDragEnabled(false);
        //jtTabelaPosto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public JFormattedTextField getJtBairro() {
        return jtBairro;
    }

    public JFormattedTextField getJtBandeira() {
        return jtBandeira;
    }

    public JFormattedTextField getJtCep() {
        return jtCep;
    }

    public JFormattedTextField getJtCnpj() {
        return jtCnpj;
    }

    public JFormattedTextField getJtEndereco() {
        return jtEndereco;
    }

    public JFormattedTextField getJtNomeFantasia() {
        return jtNomeFantasia;
    }

    public JFormattedTextField getJtRazaoSocial() {
        return jtRazaoSocial;
    }

    public JLabel getImgPosto() {
        return imgPosto;
    }

    public JButton getBtnAlterar() {
        return btnAlterarPosto;
    }

    public JButton getBtnRemover() {
        return btnRemoverPosto;
    }

    //Getters para a tabela dos Postos
    public TableModelPosto getTabelaPosto() {
        return tabelaPosto;
    }
    
    public JTable getJtTabelaPosto() {
        return jtTabelaPosto;
    }

    //Getters para a tabela dos Combustíveis
    public TableModelCombustivel getTabelaComb() {
        return tabelaComb;
    }

    public JTable getJtTabelaComb() {
        return jtTabelaComb;
    }

    public JFileChooser getFc() {
        return fc;
    }
    
    //Cria Option Pane com mensagem de erro
    public void showError(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        btnLimparPosto = new javax.swing.JButton();
        btnRemoverPosto = new javax.swing.JButton();
        btnInserirPosto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAlterarPosto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabelaPosto = new javax.swing.JTable();
        imgPosto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtTabelaComb = new javax.swing.JTable();
        btnImgChooser = new javax.swing.JButton();
        btnLimparComb = new javax.swing.JButton();
        btnAlterarComb = new javax.swing.JButton();
        btnRemoverComb = new javax.swing.JButton();
        btnInserirComb = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtCnpj = new javax.swing.JFormattedTextField();
        jtCep = new javax.swing.JFormattedTextField();
        jtRazaoSocial = new javax.swing.JFormattedTextField();
        jtNomeFantasia = new javax.swing.JFormattedTextField();
        jtBandeira = new javax.swing.JFormattedTextField();
        jtEndereco = new javax.swing.JFormattedTextField();
        jtBairro = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setText("CEP");

        btnLimparPosto.setText("Limpar");
        btnLimparPosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPostoActionPerformed(evt);
            }
        });

        btnRemoverPosto.setText("Remover");
        btnRemoverPosto.setEnabled(false);
        btnRemoverPosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverPostoActionPerformed(evt);
            }
        });

        btnInserirPosto.setText("Inserir");
        btnInserirPosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirPostoActionPerformed(evt);
            }
        });

        jLabel1.setText("CNPJ");

        btnAlterarPosto.setText("Alterar");
        btnAlterarPosto.setEnabled(false);
        btnAlterarPosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarPostoActionPerformed(evt);
            }
        });

        jLabel3.setText("Razão Social");

        jLabel4.setText("Nome Fantasia");

        jLabel5.setText("Bandeira");

        jLabel6.setText("Endereço");

        jLabel7.setText("Bairro");

        jtTabelaPosto.setModel(tabelaPosto);
        jtTabelaPosto.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtTabelaPosto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTabelaPostoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtTabelaPostoMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtTabelaPosto);

        imgPosto.setForeground(java.awt.SystemColor.activeCaptionBorder);

        jtTabelaComb.setModel(tabelaComb);
        jtTabelaComb.setName("j"); // NOI18N
        jtTabelaComb.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jtTabelaComb);

        btnImgChooser.setText("Escolher Imagem");
        btnImgChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgChooserActionPerformed(evt);
            }
        });

        btnLimparComb.setText("Limpar");

        btnAlterarComb.setText("Alterar");

        btnRemoverComb.setText("Remover");

        btnInserirComb.setText("Inserir");

        jLabel2.setText("Tipo de Combustível");

        jLabel9.setText("Data de Coleta ");

        jLabel10.setText("Preço de Venda");

        try {
            jtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 815, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimparPosto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarPosto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverPosto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserirPosto)
                        .addGap(218, 218, 218)
                        .addComponent(btnImgChooser))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(jtRazaoSocial)
                                .addComponent(jtNomeFantasia)
                                .addComponent(jtBandeira)
                                .addComponent(jtEndereco))
                            .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116)
                        .addComponent(imgPosto, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimparComb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterarComb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoverComb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserirComb)
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimparComb)
                            .addComponent(btnAlterarComb)
                            .addComponent(btnRemoverComb)
                            .addComponent(btnInserirComb)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jtRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jtNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jtBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jtCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(imgPosto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimparPosto)
                            .addComponent(btnAlterarPosto)
                            .addComponent(btnRemoverPosto)
                            .addComponent(btnInserirPosto)
                            .addComponent(btnImgChooser))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarPostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPostoActionPerformed
        controller.updatePosto();
    }//GEN-LAST:event_btnAlterarPostoActionPerformed

    private void btnInserirPostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirPostoActionPerformed
        controller.addPosto();
    }//GEN-LAST:event_btnInserirPostoActionPerformed

    private void btnLimparPostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPostoActionPerformed
        controller.clearPosto();
    }//GEN-LAST:event_btnLimparPostoActionPerformed

    private void btnRemoverPostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverPostoActionPerformed
        controller.deletePosto();
    }//GEN-LAST:event_btnRemoverPostoActionPerformed

    private void jtTabelaPostoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelaPostoMouseReleased
        controller.selectPosto();
    }//GEN-LAST:event_jtTabelaPostoMouseReleased

    private void jtTabelaPostoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTabelaPostoMouseClicked
        controller.selectPosto();
    }//GEN-LAST:event_jtTabelaPostoMouseClicked

    private void btnImgChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgChooserActionPerformed
        fc = new JFileChooser();
        controller.selectImg();
    }//GEN-LAST:event_btnImgChooserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarComb;
    private javax.swing.JButton btnAlterarPosto;
    private javax.swing.JButton btnImgChooser;
    private javax.swing.JButton btnInserirComb;
    private javax.swing.JButton btnInserirPosto;
    private javax.swing.JButton btnLimparComb;
    private javax.swing.JButton btnLimparPosto;
    private javax.swing.JButton btnRemoverComb;
    private javax.swing.JButton btnRemoverPosto;
    private javax.swing.JLabel imgPosto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFormattedTextField jtBairro;
    private javax.swing.JFormattedTextField jtBandeira;
    private javax.swing.JFormattedTextField jtCep;
    private javax.swing.JFormattedTextField jtCnpj;
    private javax.swing.JFormattedTextField jtEndereco;
    private javax.swing.JFormattedTextField jtNomeFantasia;
    private javax.swing.JFormattedTextField jtRazaoSocial;
    private javax.swing.JTable jtTabelaComb;
    private javax.swing.JTable jtTabelaPosto;
    // End of variables declaration//GEN-END:variables
    private JFileChooser fc;
}