package disciplinagui.view;


import disciplinagui.controller.DisciplinaController;
import disciplinagui.model.TableModelDisciplina;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DisciplinaView.java
 *
 * Created on Oct 29, 2011, 1:49:00 PM
 */

/**
 *
 * @author andrea
 */
public class DisciplinaView extends javax.swing.JFrame {

    private TableModelDisciplina tableModelDisciplina;
    private DisciplinaController controller;

    /** Creates new form DisciplinaView */
    public DisciplinaView() {
        initComponents();
        tableModelDisciplina = new TableModelDisciplina();
        tableDisciplina.setModel(tableModelDisciplina);
        controller = new DisciplinaController(this, tableModelDisciplina);
    }

    public JTable getTableDisciplina() {
        return tableDisciplina;
    }

    public JTextField getTextAno() {
        return textAno;
    }

    public JTextField getTextNome() {
        return textNome;
    }

    public JTextField getTextNota() {
        return textNota;
    }

    public JComboBox getComboSemestre() {
        return comboSemestre;
    }

    public void showError(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollpaneTable = new javax.swing.JScrollPane();
        tableDisciplina = new javax.swing.JTable();
        labelNome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        labelNota = new javax.swing.JLabel();
        textNota = new javax.swing.JTextField();
        buttonLimpar = new javax.swing.JButton();
        buttonRemover = new javax.swing.JButton();
        buttonInserir = new javax.swing.JButton();
        labelAno = new javax.swing.JLabel();
        labelSemestre = new javax.swing.JLabel();
        comboSemestre = new javax.swing.JComboBox();
        buttonAlterar = new javax.swing.JButton();
        textAno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableDisciplina.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDisciplinaMouseClicked(evt);
            }
        });
        scrollpaneTable.setViewportView(tableDisciplina);

        labelNome.setText("Nome");

        labelNota.setText("Nota");

        buttonLimpar.setText("Limpar");
        buttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimparActionPerformed(evt);
            }
        });

        buttonRemover.setText("Remover");
        buttonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoverActionPerformed(evt);
            }
        });

        buttonInserir.setText("Inserir");
        buttonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInserirActionPerformed(evt);
            }
        });

        labelAno.setText("Ano");

        labelSemestre.setText("Semestre");

        comboSemestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        buttonAlterar.setText("Alterar");
        buttonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSemestre)
                            .addComponent(labelNome)
                            .addComponent(labelAno)
                            .addComponent(labelNota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboSemestre, 0, 326, Short.MAX_VALUE)
                            .addComponent(textNome, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(textNota, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(textAno, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonInserir)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonAlterar, buttonInserir, buttonLimpar, buttonRemover});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelAno)
                    .addComponent(textAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSemestre)
                    .addComponent(comboSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNota)
                    .addComponent(textNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInserir)
                    .addComponent(buttonRemover)
                    .addComponent(buttonLimpar)
                    .addComponent(buttonAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpaneTable, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoverActionPerformed
        controller.remove();
    }//GEN-LAST:event_buttonRemoverActionPerformed
    
    private void buttonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInserirActionPerformed
        controller.insert();
    }//GEN-LAST:event_buttonInserirActionPerformed

    private void buttonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAlterarActionPerformed
        controller.update();
    }//GEN-LAST:event_buttonAlterarActionPerformed

    private void buttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimparActionPerformed
        controller.clear();
    }//GEN-LAST:event_buttonLimparActionPerformed

    private void tableDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDisciplinaMouseClicked
        controller.select();
    }//GEN-LAST:event_tableDisciplinaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAlterar;
    private javax.swing.JButton buttonInserir;
    private javax.swing.JButton buttonLimpar;
    private javax.swing.JButton buttonRemover;
    private javax.swing.JComboBox comboSemestre;
    private javax.swing.JLabel labelAno;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNota;
    private javax.swing.JLabel labelSemestre;
    private javax.swing.JScrollPane scrollpaneTable;
    private javax.swing.JTable tableDisciplina;
    private javax.swing.JTextField textAno;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textNota;
    // End of variables declaration//GEN-END:variables




}
